apiVersion: v1
kind: Service
metadata:
  name: kfserving-webhook-server-service
  namespace: kserve
spec:
  ports:
    - port: 443
      targetPort: webhook-server
  selector:
    control-plane: kfserving-controller-manager
